{
 "title": "my dashboard",
 "time": { "from": "now -1h", "to": "now" },
 "panels": [
  {
   "title": "1시간 동안 사용된 모든 노드의 네트워크 I/O 사용량 총합",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[1h])) + sum(rate(container_network_receive_bytes_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1시간 동안 사용된 모든 노드의 메모리 사용량 총합",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1시간 동안 사용된 모든 노드의 cpu 총합",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}