version: '3'

services:
  dev:
    image: dev
    container_name: dev
    # command: "sleep infinity"
    command: >
        spark-submit 
        --py-files /etl/dependency_packages.zip
        --conf spark.hadoop.fs.s3a.access.key=${SPARK_HADOOP_FS_S3A_ACCESS_KEY}
        --conf spark.hadoop.fs.s3a.secret.key=${SPARK_HADOOP_FS_S3A_SECRET_KEY}
        src/temp.py
        temp

    ports:
      - "4040:4040"

    environment:
      SPARK_HADOOP_FS_S3A_ACCESS_KEY: ${SPARK_HADOOP_FS_S3A_ACCESS_KEY}
      SPARK_HADOOP_FS_S3A_SECRET_KEY: ${SPARK_HADOOP_FS_S3A_SECRET_KEY}
