services:
    extract:
        build: .
        volumes:
            - data:/app/data
        environment:
            - KAGGLE_USERNAME=${KAGGLE_USERNAME}
            - KAGGLE_KEY=${KAGGLE_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - BUCKET_NAME=middle-dataset
            - DATASET=bwandowando/common-password-list-rockyou2024-txt
